import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Header from '@/components/header';
import Footer from '@/components/footer';
import { Toaster } from 'react-hot-toast';
import UserContextProvider from '@/store/userContextProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster
          toastOptions={{
            style: {
              background: 'rgb(55 65 85)',
              color: '#fff',
            },
          }}
        />
        <div className="sections flex min-h-screen flex-col justify-between bg-cyan-950">
          <UserContextProvider>
            <Header />
            <section className="main-section mx-12 lg:mx-24">
              {children}
            </section>
            <Footer />
          </UserContextProvider>
        </div>
      </body>
    </html>
  );
}
